---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app teslamate
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: teslamate
      version: 7.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home # TODO: migrate to bjw-s
        namespace: flux-system
  dependsOn:
    - name: ingress-nginx-external
      namespace: network
    - name: nfs-subdir-external-provisioner
      namespace: kube-system
    - name: mqtt
  install:
    timeout: 2m
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  releaseName: *app
  values:
    image:
      repository: teslamate/teslamate
      tag: 1.29.2
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: "teslamate.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "teslamate.${SECRET_DOMAIN}"
            secretName: "teslamate-tls"
    env:
      MQTT_HOST: "mqtt"
      MQTT_PORT: "1883"
      TZ: America/Denver
      DISABLE_MQTT: "false"
    envFrom:
      - secretRef:
          name: teslamate-secrets
    postgresql:
      enabled: true
      primary:
        livenessProbe:
          enabled: false
        readinessProbe:
          enabled: false
        persistence:
          enabled: true
          storageClass: nfs-client
