apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: teslamate-secrets
    namespace: home
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:1hTXW9Xsj3BNTGGueI/XTZkltk8nb9keiQXxxGa1FgigQn/7sWOOR8IM0cNa9mTv9+WuZr2GfNNQoNc7YQlD5Q==,iv:dFTqik5w+L0oN+Kj0e4LUGb2WwBv7C5rr8LJYEQnm18=,tag:8qPHx/Mn2BxgeLeRrWQXhA==,type:str]
    DATABASE_PASS: ENC[AES256_GCM,data:uIOJO/esWiTTjeZ/eAQuxMHEZUHYQjMzASa+8cBhbJY=,iv:78GMbk8NRV6TmmkpUkx5zgZ2Af1geFfxDQiDCG5ZZQ0=,tag:RZlCWrFytw/wQT6n3yU6ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbS8zVHFDeGJjVWdUejlE
            V3lHYUFKSmNXU0RhdzVwRHNZSjN3cWJoNmlRCnB3SS9lUlRLYjVucmw0UUFaZG96
            L2lXZGlKdGh2NUNVMXJjVnc5eURGVzAKLS0tIFU2SmJBd252bDN1cTlDcHVmSXJM
            WFhibHF3TnhIM2lGWExxdTJVbG1wWWMK6DJcckilGy6ux+dg5mZ4zcluZQ0PnBJ3
            LkXgRUQas3lUF+weaNUrjjkyKhZlk4xlPbOvhBApwPuVYQGyvbMaeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T06:04:47Z"
    mac: ENC[AES256_GCM,data:gn777Xo8Cjmbk0X4pSCdaLTQNBVZTZvIhBGxVD2D2p2gQZqgVg4FBzzlskFfcVFtHtVokgfzq5VXKF/PALHu0PzZa231VLvxEENuwxIGzf1a3IhXh6zmFeTq2b7jXAEXJAPRnixUV3YdYnMb251640KBCWVjhHlZ+omqye1PPhE=,iv:4+QSDars5iZyt1ofXn28GnJxLyRmp20hNwPUNQCnbEE=,tag:8Hbtl1avzTMQOL9OsrsUZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
