---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://releases.rancher.com/server-charts/stable
      chart: rancher
      version: 2.8.4
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
  dependsOn:
    - name: ingress-nginx-external
      namespace: network
  install:
    remediation:
      retries: 3
    timeout: 30m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicas: 1
    hostname: rancher.${SECRET_DOMAIN}
    ingress:
      enabled: true
      extraAnnotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
