apiVersion: v1
kind: Secret
metadata:
    name: palworld-secret
    namespace: games
stringData:
    SERVER_PASSWORD: ENC[AES256_GCM,data:m9+mga2RuyF7vEEXAtOChA==,iv:NdkqdFByLlynnUnAZGo58VlFrj0BWDc8gcH+AgBPdeE=,tag:hYOpIxEBcPvY+0LOxPgUpQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:l2Hs1W7bGVNAIXvG4TXNos8wQRKF3KZz,iv:qK59haSPaz+WdccRF+x4XqRMZElk5Szl+Lu7xidPWIs=,tag:0qurgPWEHA7TEyYhSQ591w==,type:str]
    SERVER_NAME: ENC[AES256_GCM,data:2WaBX+M5pIZXLmM=,iv:+2e/5pSXcdo29gdXfctpUnbKWMtLTyM4Hf4cVgKGNpM=,tag:wo+zZSGiI5gJWPGk97iQKA==,type:str]
sops:
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSGdXMTczei8yYnQzcU8x
            eGgvMHVSWkxLV1ZRSHpacFVudmFpa2luNmtnCmhBczhTdzhrS0F4RSt3ajNCYVgz
            RWMvcjdOdDNXVVkxN3RNb0l5U2lhNDQKLS0tIFZFdVRPRVpEODVCRjRKaXRRZVB4
            VVg0VnNGL0dlemlsZkFPd3Q1dHk0TTgK30eIbNAot2vhBk0rB0JvZa8uM+riIy8u
            oYitTkIZpaIPMJ4cW3UiKd2EZOo+tF21eSswr/Ogn/MLM1rvdDXHFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T15:17:54Z"
    mac: ENC[AES256_GCM,data:pNNkP3Z0iPjLUnAL1fMITGE8FejXuNXa8SLY4dOHvjgtpNl1DmAMLzm7PDG7C8ycJ1Vjd6kLvf/MOO7jPL28O9C1hH1t0C28wi60oS4wUCz7FVNd95ssjI5DW40i2QGIUJJa3QeZW9LtdZaw0TWvdf66uyWYytMwv/0mGRHxWh0=,iv:8mZyVzd0P7dxfjYfHO2vX9srnpvQ0fwyMdBaY504ZcE=,tag:3dajZ/3h7ieqcCfHcXLNqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
