---
# ClusterSecretStore for Doppler - home/main config
# Requires: kubectl create secret generic doppler-token-home-main \
#   --namespace kube-system \
#   --from-literal dopplerToken="dp.st.xxxx"
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler-home-main
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-home-main
            namespace: kube-system
            key: dopplerToken
