apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:oYK5NnXKL6NoKpqndSsMpAVUCtdMV1pI6tTAj8g4HU7zdwLE,iv:UblfBAkMWE7PT3CY0CTfELQiNF7wnZKR055O19/gZMY=,tag:w7KoR3pb4XMyhXzlRZpW1Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:xktXcOWvwUMbmYJbUGsa+jiqUR9+4ebOEF3R8LtfDoJhn18BFKp+C0oEUTSoI1B79PQN7Hu2J4oyOoIR6nQU2sbyGnW4lAOigx3ZoZihjLJKu3lcV+IF+qXkcqUgHwSwuGelcwMjsKg+JCK8D82ad3Pp4JJnrz6kBQN1Dz5TnL3xPKnbMmUPz7Z75CO9CEXgB+kygFYpWCADXSXWoJWLUc0cG2IqWjuKvZlBGR5NPw==,iv:srGdV8q89wfuLBNVsaNIaxPR9BkGLvqABuMHL0HJm7A=,tag:Z0Hux4D5nZXEiyy7AoiXoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNWlVSE00aC95cm1LMmlN
            UUZoV0xXUGtoSDdvTTNDdHZaczlHdFlmelJBCmpvWjZlS0ZZc2xvL3ZjcStzRXQw
            TTlZcDdSTjRsMGdULzR2ZGJFazE3aE0KLS0tIFVVTlJsUTZROVFGYXo2M1g3YUFQ
            NDhyUks4STRIYXlVSFdRL2FIZHdKUGcKEkUDlcWsOAIQ9Zmd0fY4mQCilxs+VYlG
            O//rr1GiP5Dcp4iBMcEs+0pAp/UnYP5mlkCBMcPinbn7wXY41ZD0xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-23T03:24:05Z"
    mac: ENC[AES256_GCM,data:vV6Vk7iYsUpy9tczdyGla2PdtTTA4O0od0dfTqg9NtZ1C5EUGKVfzRCQoa72ylyRWWK8uXFP7vgl4DQL3eM/K7vWAWXKFfjhN3Y+73sVPwVlYVKGRSD7lS0SI9/MaQRlXWzhXrVggjAejqJTLGSvfTSR80B7p2yV6JCDVCZCkRU=,iv:6F7jw0E1Fj8zdIwgU7PzKK4EkEnmmvje6OPsaBtcRvY=,tag:NQutQpuER4ogPhPqQ70ANg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
