apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:mJKrVWRb5Un8aShptWQWcIQXxPqM5+0qNjl+6VmPUAz/Upn9,iv:RvjmspIWARXado7NkzsIHQqD+wi+/PjKo6Xe1OTEo3Q=,tag:Nk1rrbOp3Kl64j2WG7X2gg==,type:str]
    credentials.json: ENC[AES256_GCM,data:Xjskda59Il5yrQaZ8NzIJ0mA6N2vtvySYPmok/yV5XL9pC60kPMLs2qCcrgtuE1acVy2uW9+hItoLWv47Qpj/hgLBNsq5xUNY8y+GFboGLt8Snp2E0ujdSGUXPzUCNR9EbSM/3Cl2DtVqWtOia2g81H7tKN8cLGUvB7rnmcw0gMQdLj7KIrDh9BmOO+mVsqeZnkdRPLRbBGCmEWfiT6wO3gFqedtQZGZJgKtZoM6JA==,iv:D/Kn35VEsvmDKY1MxR+IGyo5aqQfjNTaaz2Oz6BrUYc=,tag:uXHdrfk6jXxyn64WU7mKCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVWxLb1RpM1ZBS21HVUli
            a2pPYnFRQ082dmwybkJaQUpCZDN2WGdRL0J3CnJSdXdvVkxQcmc1WXJGcHA5ZDBl
            RWhoNFl3K3BxQjVsam9wTmZNWjB0eUkKLS0tIEMvaDQrVHYvTVlSWlU2NG5HVUFF
            azhvMlgwSjUzcUswRjM1Vm85L2N2QmsKsKtAMYJgay32WJFCA/huXCMESvxurklR
            Ofqs0KLnlZXL5u95SWMK1oGp4btdcrA+UCgpJniWLpSlZLfS0MObOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-02T00:41:47Z"
    mac: ENC[AES256_GCM,data:KC338rC41hSTyAKsLjmHSHSXGbGSUuQfv0ufv89aoMD6v/a2Gp8RiX8P8wKUJ/z9SLXLnuY7IKSBvRkdlTW0RPy6eYcd9JdwPh3Z3Zr+QKI8jzdsAZIRdDs8hwQ1e3A+yGg9Hb+UMVUC0TRo4n/Ie4Evl/jW5wXojnjxYFRCMxI=,iv:mZApWj+MGy9UrFCgEUqKq0ILTaPJL9qsM38g3Kwdpvg=,tag:vU5Gr5EF8rn6mzDbOomYxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
