apiVersion: v1
kind: Secret
metadata:
    name: clawdbot-secret
    namespace: agents
type: Opaque
stringData:
    CLAWDBOT_GATEWAY_TOKEN: ENC[AES256_GCM,data:j3GUnaHm8uYP/sU26CA5uW9bnWBIFPFZv+Kf/GZ1ys0=,iv:yFxlCGmggUvDzlHI3prYm5mp49dVHthIh7DFnh2aA90=,tag:rdx0C4V7+0+Oe8CMIjBGZg==,type:str]
    DOPPLER_TOKEN: ENC[AES256_GCM,data:BJkwa6x9AxVFhBCnZlcdXfWwg3mGa/aczqrjLls9rTH8ZHuTS/quLTjKbUIlPh8FQw==,iv:rTwsff90mgHmtqZySXifwmTQy5mvdY4AEBtLKCDUv4Y=,tag:VnZzr95JBmdFkydM93whIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSU4zZnI3RjdXdFVMd2Z4
            aHpaTXhKOGJmdzVxMEtIS2EveGpjRHFYaW5FCng2VlN1UjIrU0tOMllCbEZ5RzFi
            QzREMjI0UUxQaE8vRVZhSkpFYW9DN00KLS0tIG11SkE4elhFLzZvbk45dWRZb1Ix
            ekxOQ0xNeUk4V05KRkxTT3FKUWpqMmMKjEikt47t7FfWt8/WPlmtkHhGvJ7/S6T1
            5AifYt7eqH2DuOrYnvB2b+pYQgNtKR7k5ECVX9byH98kca/VAaTlQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T04:53:16Z"
    mac: ENC[AES256_GCM,data:XUDBYCg9W4OFtMqzKAWmQifq9AnCL2BbJ3Xx54+QDJxLaUvqcPoLPPk1cFUke17LxDXpj5H30oCiQYs6QtmNQjwkAfefPWQByreZrlb4gmb0YhIEU+h+mBq1bH+7mHNCAbPgIfZ+w748GKkyT37e29u9igN9dGlTcjizDS11+80=,iv:wJn+/f02v2kLPY2XweLByZzk6B8Gs/4+JswNley1HAw=,tag:VbrsN+FVwX/mBseluiR6dQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
