apiVersion: v1
kind: Secret
metadata:
    name: clawdbot-secret
    namespace: agents
type: Opaque
stringData:
    CLAWDBOT_GATEWAY_TOKEN: ENC[AES256_GCM,data:XAOMhRlKpsTFF4s8bWQKM+yL/5mt8jUHgUo7LsYnohk=,iv:c4dnrZ6txmDEW3KfIaXDI/joQ/RwCvUmX2dPpn74J38=,tag:KCELdSHngfHHUAQoPLdaLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTa0VZSXlzK0pzLzR6UGYw
            dTFHOVlnT3RkSUNZUTBPd0tZdkgzc1NvYkNBClhTeUc5TkxwcU9FOWRQeXQ0Ukhk
            dHdxcjl6S0Y4ZjkrSkVhbFh6VFpjU28KLS0tIE9SMnpiS0dqQU1Zd3FMd3Y2akZL
            VjZBamtRbnFWUk5vd3lDb2crcE0xTE0Kdgs+W1iOPAV6DcWL/ZKcu1RiFgiTRm33
            MMb/dPahOR/Wi7QD/mqqppZXRaUVm4bHujXE5Zv8cgMm/T6CyN7LIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T01:25:38Z"
    mac: ENC[AES256_GCM,data:qMAifu2OZ6b2TgBjIbk9A8vESS54PPbU0rI6JmFtnWpvhQwHLTHONiHMEYgyuTjCVk5hkoucj1KKUu7pHRxAFdoU/uofti4fgPlwxV7VBGsKOvFEJwUUIeJJH4OM/Wf1+a2n43+KApsW9RMQgELilscjJGDfUzxmrZlmWzaJadQ=,iv:Rgp6jUz2hHMgWnB9NhRNNgGS8DINJdDCcOBS2h7j970=,tag:oae+gZeA83O8370u6hSkMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
