apiVersion: v1
kind: Secret
metadata:
    name: clawdbot-secret
    namespace: agents
type: Opaque
stringData:
    CLAWDBOT_GATEWAY_TOKEN: ENC[AES256_GCM,data:j3GUnaHm8uYP/sU26CA5uW9bnWBIFPFZv+Kf/GZ1ys0=,iv:yFxlCGmggUvDzlHI3prYm5mp49dVHthIh7DFnh2aA90=,tag:rdx0C4V7+0+Oe8CMIjBGZg==,type:str]
    DOPPLER_TOKEN: ENC[AES256_GCM,data:BJkwa6x9AxVFhBCnZlcdXfWwg3mGa/aczqrjLls9rTH8ZHuTS/quLTjKbUIlPh8FQw==,iv:rTwsff90mgHmtqZySXifwmTQy5mvdY4AEBtLKCDUv4Y=,tag:VnZzr95JBmdFkydM93whIA==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:SAeBRyUxFqCtVxnmj3ice4HPkHYlVcONSO7eeJb5fk3Js23jz1y/++rngkHeAD9IMZPxIg410PaaE+2gb5DwQBsYPLOjvdnOVr/Xn3pZLPMYOLKt6Okt/6v8A3ZGrDcd6uRjeKOfMus99WF1,iv:UIze8SErtnsc9iwki8lnH6iIP284wunvmm/Li/iWmus=,tag:TVFIQDj+RpM6m8b0xOJb0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSU4zZnI3RjdXdFVMd2Z4
            aHpaTXhKOGJmdzVxMEtIS2EveGpjRHFYaW5FCng2VlN1UjIrU0tOMllCbEZ5RzFi
            QzREMjI0UUxQaE8vRVZhSkpFYW9DN00KLS0tIG11SkE4elhFLzZvbk45dWRZb1Ix
            ekxOQ0xNeUk4V05KRkxTT3FKUWpqMmMKjEikt47t7FfWt8/WPlmtkHhGvJ7/S6T1
            5AifYt7eqH2DuOrYnvB2b+pYQgNtKR7k5ECVX9byH98kca/VAaTlQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T04:57:25Z"
    mac: ENC[AES256_GCM,data:0BvNWId2hxGb2T3R2B/qHMudbSp4pO6wURgPe0u2xr7N8Gl36TN7fvOGbP/L9EfjxeZ37QCvmfWIbYVv0DyEKxCmomN7GWwfLAu+BOuCGj/dSt477uRuQh+DBmxRmqmOVxILvQRdAidhgkUzAi1BJZ9CyDZjdildumyu1J2ZNxA=,iv:H3X11x9fEIVqAXeECc8zo0MDiw4fiUBgSSTbH7a+AsM=,tag:yD/8GHhLg7uBB29tUu9f5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
