apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
    namespace: home
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vBWS0EjALCbOSPxIIxjmR8YkrTCHTwq+yWLSaU8Ksw==,iv:edUfeAPVgNtc/EkR0dqB2C6qNoloujkYChnbroxA9CQ=,tag:A5WK2P4KQTpQH5dvUg56vQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQc25sUXdINDllRXdWNXEw
            OTc4NCtUMlJWTEJGNU1VS3hRRUl3V2F4c0F3CjgrOEVRZlQvVjZIZm0vc1F1Qytv
            eGVGbzlHSjY4aWdHVmlBR0xvbXpmS28KLS0tIGtOYTJER2VTeDVRUzZZd2pRVXNZ
            cWpKdVRaZC9aak92a1FwdUJXUm5kUGcK781ckKBV0mRk8NS8OTnUKbC0oJTusDq/
            m6TKI67sclYP/f4S0uFE8TKmkZAq9Tj+LhPAS3Gpaqbt7xd3uWyFXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T22:26:38Z"
    mac: ENC[AES256_GCM,data:Y2Vr6BL4oS+fr6aRY9pwdWWsWmsTKOBJBCVyA3ALNJipoqJ8DMFMLFcTx6s7wVYDst6AfjT+bm8bfJ6ELqlhHa/jq9p88xxKvd6AUgsO5dEv3POkxcHpY3oUPnEDlACP6NUR5Y4RmwdjsLXwXV4glBvN4Rin/I2jQvpJGmuOLsY=,iv:2Hx6+UK9n64wonDxXC/BTTXmBGffiOtscNQTq6HV9Zo=,tag:H91/GyCAO2T4zpW1vBK5jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
