apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
    namespace: home
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:nwgLL+iaGucak2OXBzNCVkTmgyo/iQK+FRY7NTt2U38=,iv:9U7XRmEa9wL+PlDitzQclGFWfhWaQIdu46oWX1lPJVY=,tag:WtwzuaZojH3mDjEszJTm4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrV2w1TDhKZzhlRUhJdHQ5
            Q25zUHNwTVVEUTZETHZSeDY0YUZoRVgzNEhVCmx1R2FQSENURVc5eGQ5RTNQc2I5
            bjQveVR6OE5sdkpPS3orcStrcWZMNkkKLS0tIG9MUVhzbXJpTUdkdExRbmVSZXRH
            ZkpZSkRydnBpMkxxWXg3SWJTalQ3c00Kkj9p5NDo2cDKrfys+YsywXmufmaMW7Az
            S8m5rRbN3oTgEszObcI7N6IICyv9mV0CFk7VqEoLyciRFuEboiGfHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T19:15:44Z"
    mac: ENC[AES256_GCM,data:qv7CQlIs2CAgO1hx2usl2KguySqV/emKgNJJAOy8Tu5rbcECef0TjZ3dX6HVPLocs3+AH272QrrarROEGMVQ77kDPzRPwDBsOQzvHEnX4i8ZFiRdiXTXhG+0MWHB+fgxqM3JkFJ/xs/0hTa7bpAW572CEcIDz6dt3/F+y4NnbcQ=,iv:GFhUMrh3xpBrGswxTvkrO6/nVkxtxDBTy6OhMotrelU=,tag:5iLPIFR95YeGs9zPtJm0Aw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
