---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./home-assistant/ks.yaml
  - ./mqtt/ks.yaml
  - ./teslamate/ks.yaml
  - ./frigate/ks.yaml
  - ./esphome/ks.yaml
  - ./ema-reader/ks.yaml
