apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:2NlvGEfDf0fHysW9+9oI8SCTOM9NqlNFDh8YXDWWCcTZF2RrGNOozQ==,iv:P4Q+nWQw6ukgfijiTyw0r4lQckt2RM/C0snmBskbxIc=,tag:xPrhTxXh8kcar2rer+LCBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VHlJaHhQem14U0RsY2VV
            SzNLZDhQY3MrcnBQbVNnYlFjdjF2dzUya25nCno2ZmdKRjBoaGtCN0lLeW4zQlBQ
            cU9naEt5OHVpTEw3VVJsVTJ0ZVVnOUEKLS0tIFJwRVE0YmkyLytJNW5LVC9VNUp6
            UW1RaElVcUNIenEwcGVYM2NYRHBZQm8K+CSlbIpDmgqruh8epF14TmH9OUBpcH1c
            biwNEShDqvaWQ2LHQY+zPhX+TpP927MOGTrNZdzGT7/OwLl+mAmOtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-23T03:24:05Z"
    mac: ENC[AES256_GCM,data:QBYreuU1y2nHF3eiAv971kW0Mtluv9G3fXnDgrP4kXzWP2RZYHoiEfUkM780OTIPFxq7EunPLR7NFlbNYTCz8fjDcic64GXhtao9ArjMZYZN6MDgW7XS6A0IWfWTM/lkTqS/6JSkbiuYXMXvcN+1aRQNd9AahonRBUimW+X1aOE=,iv:J5pf0NFBbTDn9nQ9wA4EQeDFBHpswjehj+JPKcmKDNw=,tag:9ksUMcL3el+sAo42x13i+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
