apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:97i9JcH5CsCV/+gS6kMNX5+m51soxF/pVS0Kon+1mgSOYYy9OHUu2Q==,iv:uupf/SKXIROiwysOR18xUNDiITrdrJFNqOspzkbcrCs=,tag:yc0zSYVSqo2Ah3CXqxHVbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTVpFODNRbGJxM05hRnc2
            elBXSVkzWUFsODJOM1V3bWd3cURnRlJBRDA4CkptODRBTEhBcFM4ZForM3dmTGpo
            aG1KSWFPT2tXd0tlSFJWL29qYVB1eDAKLS0tIE1Vc25CMUx6ZHFwb2hnck1sTlQy
            REVQV2VTU08rT0ZWWFBnbDVHeEN3Sk0KpFY1IG7r5/uJ8KhqkiIne3nwyb5/VGu1
            wi3scH1PWNIg4Xs7dCTyksDTQxWzYQsh7T2i5Qne5pD73A17OApPJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-02T00:41:47Z"
    mac: ENC[AES256_GCM,data:oacm6FKvHrP8n/sV5cXqfhcrNKUtBTOELRq5w3NFrCeYHRTQyGSKNJggvJtXihpAFvF/OapJeefTfsuSDxYgEPWo86TfTX3wPc3d+xEEho5qjrrV7D2pMdL5DenJ5rh0GlBeMrcYyLz67VVkjFMFZxe+gZr6E8ZBf2qBteBDTB4=,iv:eyQzATnCyo0JV/YmY70jxs6K9M84FGtFoV5DcBD4Kjs=,tag:mh3t0IbFflUYWj1/PtPG5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
