apiVersion: v1
kind: Secret
metadata:
    name: valheim-secret
    namespace: games
stringData:
    SERVER_PASS: ENC[AES256_GCM,data:QNiIHflJ64HrDv1BT8FbMw==,iv:UkNQnK9uQ5V8ILckPmlZt2Bk+KfIRi4/bRNpXrP4CTk=,tag:WN65Lf7hQ5kZhzPcuL69kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOVI3VzlxbTg0ckhnZHZH
            T1N2ZVJrTmtPblI4VTRUTjlqYk4yQlNETVJnCm5kdWJsVU9mK0N4cUd1cnVKSlNK
            V0lxYVZHSmhsakNlRkE0QU1GdU4vV2cKLS0tIGlhNmhicXVQM2U5bnhmbkoybVp2
            alhJR2tvUUVhRFBqTkhidUNnaWhMeDQKlHjiVblpQ7lXlNQnddLXIF0Qbv3Ab4kc
            Oxbz9l67UXBQAD8kQH4lmdNTlOON7pSSzSqwvIsZ8W2hEHF2tTcbgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T03:56:15Z"
    mac: ENC[AES256_GCM,data:jn4VrGNe5gZXaokfPMFksApuw80nVQPA9q7fMgnKQUX9bqhGU1VOYX6aZUvaxHbz2G9ApqP9eAkw7HkH6C6WQNR0DnwmPIy+Ar4Je475P1F/BTXab8UGBXCYJyEdEeQm/7FNPktWJriHQJBjjI35QAsx4U7DzQjHOVSe6duc6sg=,iv:RoYn7u9TUM5el1VMziFaBO9upPTY6Fa4Ztg/8/GJdc0=,tag:R3aqOuuEL8hl0FPz2hi4/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
