apiVersion: v1
kind: Secret
metadata:
    name: valheim-secret
    namespace: games
stringData:
    SERVER_PASS: ENC[AES256_GCM,data:ih1PniNE0pZyzdnstQgnGnbiDdw=,iv:UjYUzxvWm7MEPfoNlag1BiFXqLHzCDb/d4VFzn+IkxE=,tag:laPZ8Tu/1nEPZJ9T01LeJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaXAvRUxFcVBNTklCUnVN
            Unk4aG03eEh2SVFSZ0taaHQzRzFSUzFEQkZJCkhoWHFNaDNJUEJraWJSYlZGdXlC
            a3crZG01WTNjeWFXdmJQeDArVUdXQlkKLS0tIEM2aU9wMGl5QVZaSmpKTHdzZzNm
            Y2RaWFRlSE95YkhhZURHS05uSGJNNW8KjhGWR1ABtkQJFMZ4S8fl3zRsKvHDu31P
            Zr7UnDrnt3qxOZLyLE7KfAa1pflYYgw3aKIaTRvatJJBZfBzB69TbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T04:18:49Z"
    mac: ENC[AES256_GCM,data:t+aWusyj54r0TpwukCrPFWrUXJWfwK9zvMIUzhRuysKmMETXbEvD7I28OFTAuKstOXBYGt0njUSw/IR3Eqf7VJPgaSHXalfAIfj6H9LvpW9H3cLJnNB7QDyHVB4W534E1tgpdjlPmR0gXmF9CQUvcnN+jRhvH7aJENzMGKrWeq4=,iv:q7DR0lXHuvOrt4qV54GywnXQoHaz0Ae7qCBF/YBt65o=,tag:5ZdAqPA6yXYt8l3zNcCuzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
