apiVersion: v1
kind: Secret
metadata:
    name: valheim-secret
    namespace: games
stringData:
    password: ENC[AES256_GCM,data:Rbv0imX6neAShh8EYUmjeEpQqGQ=,iv:eCWnNcmCUvamx0qDt5L+cRf3tMnLqaVi6cy17vbFw34=,tag:wnBgU3k9PlcdknfcufEVrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM01LVmV1bURLQ21SWHlZ
            ZnppSVVHTHBpZm1EUVNWa2Nqbk9LYjNtRzBVCmhLT3JkS1JjMm9QRWZHb2hXWnVW
            LytOWnZMVzdweEtwVnM0T3ljM2hNeVkKLS0tIEdVcUlKamZEQ3RCV25YRFM3ZlhD
            WEdrNXN4cVRqSU9sdWZGcURpWU9qekEKnoSQctliYTjrsMag0J+PMqyfdJdfweQ3
            30WfBEjXS4PnYgtTww75131JjVWfCDbexwR0yYf54M7BF116qyCaJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T05:15:34Z"
    mac: ENC[AES256_GCM,data:mtnpLJpziaEsp0ZuCAoz8Nm9U7vZnRxM5pgzLBPnjJLywSFrmkB67fxO4igtS8NSPMV3DuMk3B+Rw3XkeYkUzKlgmGrEKynjQxGsXEKO/CySmkmmqPqxC47OngoQTJfxsgLvpQaCdJm2/JMLx8FYH/EW1K+fj8Qu44sd30f0HZs=,iv:1qWWY/46nok6G0ftBJzIZSRix73M1irz6OKxCGfGHqc=,tag:IEii42ATcKStyl7lf6fFfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
