---
kind: Service
apiVersion: v1
metadata:
  name: nas
  namespace: networking
spec:
  type: ExternalName
  ports:
  - name: https
    port: 443
    targetPort: 5001
  externalName: "${SECRET_NAS_ADDRESS}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nas
  namespace: network
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    cert-manager.io/cluster-issuer: letsencrypt-production
    # external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
    nginx.ingress.kubernetes.io/server-snippets: | # proxy_pass
      location / {
        proxy_pass https://${SECRET_NAS_ADDRESS}:5001;
        proxy_set_header X-Real_IP $remote_addr;
      }
spec:
  ingressClassName: internal
  tls:
    - hosts:
        - "nas.${SECRET_DOMAIN}"
      secretName: "nas-tls"
  rules:
    - host: nas.${SECRET_DOMAIN}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nas
              port:
                number: 443
