---
kind: Service
apiVersion: v1
metadata:
  name: nas
  namespace: network
spec:
  type: ExternalName
  ports:
  - name: https
    port: 443
    targetPort: 5001
  externalName: "${SECRET_NAS_ADDRESS}"
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: nas
  namespace: network
  labels:
    kubernetes.io/service-name: nas
addressType: IPv4
ports:
  - name: https # should match with the name of the service port defined above
    appProtocol: http
    protocol: TCP
    port: 5001
endpoints:
  - addresses:
      - "${SECRET_NAS_ADDRESS}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nas
  namespace: network
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
spec:
  ingressClassName: external
  tls:
    - hosts:
        - "nas.${SECRET_DOMAIN}"
      secretName: "nas-tls"
  rules:
    - host: nas.${SECRET_DOMAIN}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nas
              port:
                number: 443
