apiVersion: v1
kind: Secret
metadata:
    name: enshrouded-secret
    namespace: games
stringData:
    serverPassword: ENC[AES256_GCM,data:2QC9PsC/1wu1mB7hZ/fyHHoaT02dhKp/w4LnuEg/lZ0=,iv:JnmmuJg+XwQROrXI8zSLAS+yqzQRnOelhklyaAVXVZo=,tag:Zd8OApYc2TjCueIaawrcyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eXhjMytHL1h1Qk5qcDhU
            UDdzc0pvZGdkYzFiWUpjQ3ZzNDIvYVd4ZGowClEzaGczU3M5alFpSlVvREk0enRQ
            STM2bDBscjh4aElJRDhHdm1MVmxhVWMKLS0tIDNqVTkrRGxGVCtUS1ZMNmhXdnVR
            cDJVRDdSUUVKODdzcXVaZ0pDYkhrc00KY11QLoNLeraAhwbmYY5v08HVdYSUxzig
            Jso+rnvx9fvZCIv7GZlTfgsytF4Dpvz5WErT7m1rnZrFQPzn4ZtMaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T17:27:08Z"
    mac: ENC[AES256_GCM,data:gDe5m9TMQzdGfDLB/LCNqoWbWjJksooKX1tc+lvLAgC2Th81Mw1+SN3DHtJyavTXRIapSR+9fy7onETkidlClNPYaNI5hxoDrluuZiiVj0hncIBiOsmSxbPy84WyPeoU+ayQyIgCjR5NtuwXLeWTnYMkQXaJmJrxWz3WqWwYNuA=,iv:YaKdvQiHzmiu0ztTpSWhtdCiCiEmYKAryemM31Lj2WA=,tag:B3EUFUcU/TaE+wh7SAfpZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
