apiVersion: v1
kind: Secret
metadata:
    name: enshrouded-secret
    namespace: games
stringData:
    password: ENC[AES256_GCM,data:ZUPNcDDodRSRJYfuJd7gDPOa3GHFQqeVSArBKUD3UIc=,iv:P2UbA7RBF1SkwSCH3ipqxGEBF3FHvCcL2LUmZgavIUQ=,tag:rT7wJ9q4wvQEcYqRk5ZJZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGa1VLMldCajhxNWpxcGVE
            MXVQNnZBZ3pvaE1DK3liaGFwMHNVaXlvWkVjClo1TG9SYm5iU1FKanZiY0pOQ3dG
            MG1NMTVPbkxPeUtMdjJROUlWdmtDRHcKLS0tIGl4c0RWZjF4MG41akJEaHBLOHJy
            Q1U4aVUvcTlMY053RUYzMm5MVkN0alkKWWOxIXm4eLRt1+kt7Xls/X4zjCDLnGfk
            UkzxUCfPBz4rsKm069HmaGY/7CT/hwvmpwBF2418YPo5LroPkGFxqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T22:25:04Z"
    mac: ENC[AES256_GCM,data:pzlQOflheA2s97ALlTl3dsS7WTtPNYU7LEt2Pb6J2IIvdm3TuYNQllBeB3LzhXWcBbEzp/cejmctkRAvX9oK9BVPhoI50/Ex45aA5U6RFvZlvpliyVdQGPF1EmXX4s342eiJr8WdiNK8ZN9i6z0Zu9jP0YuSltIiNdrHwhf48F4=,iv:XKhkxYTdoBJ0XDfKWsy8+YiisgIvVeWNbbchnw8/VS0=,tag:wEw2yaQn6+cij6qYE9c+xQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
