---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./boilerr/ks.yaml
  - ./factorio/ks.yaml
  - ./web-games/ks.yaml
  - ./satisfactory/ks.yaml
  # - ./icarus/ks.yaml
