apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:pMcWtYv0H9PNoJySsmA=,iv:KtG91dSFCd/rqFSX7AKLnXep14KchBklt5GcXX7MfBI=,tag:pKWvHduEBp3uxQS0AYPz/A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:De+8LrqWT1Bj6A9U,iv:WSfvbfhNSa5tbV0C9UkktQ58TZNsodYYCiIiVBooOCY=,tag:PDIYk9tW1+WVZXBz3RFpRw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:emF1P9MU02cbXYSWKhgo35GRCPeT3kEkJka13e1WqKjWSdxR,iv:1vEJyRpSiwML9YR7n71rfCSD8dfkmw0T7Z6sBgD7f1Y=,tag:7mcEzhNrxv+zrPofoMBR1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RGNBRGlJSkV4a0h4Y0Qr
            ZDlKT2Z6WnQ0TDlvWmovWUtxUlM0S3psYVR3CmpnaEpnNEFwZTA3T0FVeFRvMGRF
            S1dkZWk1T0Zrc3Z0b1QrbzdwbzVSdVUKLS0tIEV3TzRTVVdhdi9BYnlGWklMZkt5
            cEZMNFh1VFF2US9IV0Vhd3FNRFlsL0UKHEsNBR63Sh8A+KIfD9h8AQL6WqV6sjWj
            26fu8QAsseFswy4BO0/LTbzmJWCMfPb65PnbvLk2z9Cc616Ba2wPVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-23T03:24:05Z"
    mac: ENC[AES256_GCM,data:Zn63TXmX2L0gvZv7DUkA6fqUmZGwimWlnajARhs3EXItFx2vG7PJ5k0IkWfgVDsv5F18ctRBQTcgrVjxNzI3bExq+MbE4gQHJBopeDbdeT9ojwh8G/3wYeX7xLlGcgtVppNYLcde7V83Yu1W9cAuD9FrhLk0D6tMTfxUuf2lV7A=,iv:ZcG3XjWkj8obnErb/PYSoCOMNQNBqW/Z45hr0tS6Ee4=,tag:/VuR2NpfnznWoUbXN+8zYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
