apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:OlTGtBrS8vvr+nNuipM=,iv:V+r5TgtiFsCFxgwwWpx7YDkyPmpUHDus29eZjFlTqRA=,tag:MUNK1SxDWCq1n6/BFkZvZw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:MfaoHHXGh3+xaO99,iv:vnvt4/nBcMObEnL1zUwwxMFM96Q4LaHnHSe9MnIckQI=,tag:8L/F7GqOUR/irWjkA8yZ+g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xoxxaSzTD8nSxRZYNbAI2cZ7OhJEAuc5mPnBK/f4OMH1zcoC,iv:Ud4zgWKH1vVz5kp7BJkGMQEgGjlnICGdi2bAGzDNNHs=,tag:4z4ngt72I9qYbkKg4QuW2Q==,type:str]
    SECRET_NAS_ADDRESS: ENC[AES256_GCM,data:46XLz4Di6XMHcLMX,iv:CnGfWPGPXFv9D6qAtsqxD2kT78rPSWg/H68Yq6ochi8=,tag:nzeyligUFGXMEXx+RuEJhw==,type:str]
    SECRET_EXTERNAL_INGRESS: ENC[AES256_GCM,data:A9lqfcFYhkKWpijEbA==,iv:I23HNe3S/k1SRu0whWfECtMHsSBOnbf8VGk6TI+UvHs=,tag:nbOlAN5ufnCUGrVNor8lVw==,type:str]
    SECRET_INTERNAL_INGRESS: ENC[AES256_GCM,data:575aEftAwt6Yr1MjzQ==,iv:Ejyu33SxNp+DK78Yc4HzDh3fduWdrXsUzCbW+bf4o9g=,tag:Rh8GRXB2rMIRb+/pPfdOVw==,type:str]
    SECRET_BLOCKY_ADDRESS: ENC[AES256_GCM,data:72BppNe33Q4rk1VEvw==,iv:Vhka8QHx3jcMyve/Jdrxh8kmP5N2QEHIN0CiEnCaPHc=,tag:+Mu9mKDggLLRpcnXmHp8kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ3orTWtxY2lvR3hHeDVj
            bEs0T21qdDN5L240NGJ5dUtjMXBHTWZwRzJFClFrU090ZmV2dWlwcmVxQSs2R29Q
            aWM1TlRmUTI0Wm4zeWxaS01VVGhxNmcKLS0tIFYwZ1N4SXZDMElBUFAyUWxyT2lx
            L0VodGh0MDZrSzlPQ2xncXRqaVNvS00KegRu/FVWgaYxj/pWljxwyNAXuSRidLTO
            F1Xhi5mtD4jHTEURIcgDxFEez//FM0FtSQxk/zzjlIFH+/B99/398Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-03T20:16:28Z"
    mac: ENC[AES256_GCM,data:Dr/JvF+Cajrlgq9kbKH708y3XSL9BVH30reZ+TSz64Cvaf4+tlCeHvlAKqFNZtAhSs4C+yaFt3tnKIB1QDLzmXVQrfU4uqMv9yfe2c89Li5/E0w6ejypEazrBnrv74bljhFNhJ1jdldorGBGDdXbyxrfKa7Q756Y/XQtmRKty7E=,iv:uE1RHpblKn8Gp2qfkQB1EdYL6aW9WlvOIra6NKhM7zE=,tag:DQ8Q+DXkQbI7ovNu/uR6bw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
