apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:OlTGtBrS8vvr+nNuipM=,iv:V+r5TgtiFsCFxgwwWpx7YDkyPmpUHDus29eZjFlTqRA=,tag:MUNK1SxDWCq1n6/BFkZvZw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:MfaoHHXGh3+xaO99,iv:vnvt4/nBcMObEnL1zUwwxMFM96Q4LaHnHSe9MnIckQI=,tag:8L/F7GqOUR/irWjkA8yZ+g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xoxxaSzTD8nSxRZYNbAI2cZ7OhJEAuc5mPnBK/f4OMH1zcoC,iv:Ud4zgWKH1vVz5kp7BJkGMQEgGjlnICGdi2bAGzDNNHs=,tag:4z4ngt72I9qYbkKg4QuW2Q==,type:str]
    SECRET_NAS_ADDRESS: ENC[AES256_GCM,data:46XLz4Di6XMHcLMX,iv:CnGfWPGPXFv9D6qAtsqxD2kT78rPSWg/H68Yq6ochi8=,tag:nzeyligUFGXMEXx+RuEJhw==,type:str]
    SECRET_EXTERNAL_INGRESS: ENC[AES256_GCM,data:palSQuZV87fi4Fk5VA==,iv:KG2tNYJGhy1RFszwWaLIiv9SfmcId8b4EwxCjwmhqmM=,tag:2M3SKlnJQKPZUnpwmIROHA==,type:str]
    SECRET_INTERNAL_INGRESS: ENC[AES256_GCM,data:s6R1uiixIg/XvoQ8tA==,iv:bH9YQiqpHFk9gnCWHZwUPGWeJXvW+vMTDxJSUisnwAI=,tag:Xojn4SNERqGt1OB2FCvEdA==,type:str]
    SECRET_BLOCKY_ADDRESS: ENC[AES256_GCM,data:72BppNe33Q4rk1VEvw==,iv:Vhka8QHx3jcMyve/Jdrxh8kmP5N2QEHIN0CiEnCaPHc=,tag:+Mu9mKDggLLRpcnXmHp8kg==,type:str]
    SECRET_DEFAULT_GATEWAY: ENC[AES256_GCM,data:nid01hF1zFbiCH0=,iv:FtuDYMCKOl7eFG4ebSQzpo59krnyQPwKlNyndzrGRBg=,tag:S37pt333etmGyrvqXoceQA==,type:str]
    SECRET_CAMERA_CONNECTION_DOWNSTAIRS: ENC[AES256_GCM,data:SLmhduhpu+UR+f8q2dvMIHNLdemWguOHdTUV3z1cCybUmpXCJgTGHDJvCC4tjic=,iv:tU5IiIl2r+lzwwKIVoXwWiPMWSLHcZ72Nbr9z5JkR9A=,tag:HIgX+GJnnqjKJA8/WukI9w==,type:str]
    SECRET_CAMERA_CONNECTION_CAYDEROOM: ENC[AES256_GCM,data:6f/CA3mcrRpnDD9XbjpdDRtYFMTInIp+5TvX6+i/tVFOhDoHfGpVEoFpSP5+RAA=,iv:LdOAyhoguxVQsAtNUYACk1o3k+P0NTwz6/HDxNy2BXc=,tag:Hfi2PJJo/Ka5B/dHxH350g==,type:str]
    SECRET_ICARUS_SERVER_PASSWORD: ENC[AES256_GCM,data:16rIZYmMSHXpJLjlSDK56stau/O+4ri+g94=,iv:ynr/zHBzXiGQS0dAAAHAqBhhjmA/uD2igzFxUr8Nvh4=,tag:cAoq6RmHgT4nTeQb6FTxbA==,type:str]
    SECRET_ICARUS_SERVER_ADMIN_PASSWORD: ENC[AES256_GCM,data:eDzRfMohmpDaZaUaVJJD8raAKkdZ4mKQ0+g6iDRDOEE=,iv:w2cvfpVM8S74OZbdF6TMO7I3NcuVGja/t/rAG1xNMOw=,tag:kX8ofgQMJXXyVmh1vdUp0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ3orTWtxY2lvR3hHeDVj
            bEs0T21qdDN5L240NGJ5dUtjMXBHTWZwRzJFClFrU090ZmV2dWlwcmVxQSs2R29Q
            aWM1TlRmUTI0Wm4zeWxaS01VVGhxNmcKLS0tIFYwZ1N4SXZDMElBUFAyUWxyT2lx
            L0VodGh0MDZrSzlPQ2xncXRqaVNvS00KegRu/FVWgaYxj/pWljxwyNAXuSRidLTO
            F1Xhi5mtD4jHTEURIcgDxFEez//FM0FtSQxk/zzjlIFH+/B99/398Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T02:56:25Z"
    mac: ENC[AES256_GCM,data:bVEweYUeoix9THjN5w2tqdC4X601ecOG/aPCHSuWuMQ6CH2/lhUPxWV3+k2TaGVPeyDJC8AwQoz4Kdpzl5/ePA5iE27MsYUj46yjoj47u2+nKb0T1c3354KeAXNQY1g7F8x2jxpcDNRPOiwZYnCmKdTMDnCJM7xz508wqXA0pfM=,iv:p8elg8OdsYyF4EqnlTISBOoXYuJL95VCj8JVxd5nAZo=,tag:Pa5qDkjcZHq/wb1MNGLI/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
