apiVersion: v1
kind: Secret
metadata:
    name: postgres-user-mealie
    namespace: db
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:nt2wZj4i,iv:mqrKQSj9e/jzgP8K6+mSwvR3o48aT7zFFM/ETdY85y0=,tag:WDY9Uy+EHibvC7dB6Q484g==,type:str]
    password: ENC[AES256_GCM,data:qsrmIsGM9MGoRGrZ7vpwNAkcQ8XaTWuMc0rA9DXjZw==,iv:4RvEE/a5UjGPnh4Ce/7ATXJLTR1Lia7XIBZxApQ31uU=,tag:LjJM5BUQopiagm8rOQMUBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUXJJY2ZLbGR3WXJkNjdm
            NEZoQ2c3ZXNzbndYN01UUUxTSUgzMk11c21nCjQyUUpnc1JaNVQ1bVh5NFNqSm16
            Q1VPNFYvUmRUR2dNb3h3UzdsY2dwck0KLS0tIGMvYm41UU1PZUlnZldQd3pmN0pP
            Y2hmQkxETDd0bE5Remx2WkJvSnAremMK7IT3eN3uHZMoHYUKmHs3krh9DogTiXVw
            mrOvMz5twgGLZHoIvapDzxZX3uZ+9Gce0ATSpHPAODnOHaSdlqkVQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T22:26:38Z"
    mac: ENC[AES256_GCM,data:yW5F2TlFgOCo+ptKTy5sjOSSh44A8X4DY0FIzkUYqwVd3vsZQ6tWl/gJSqLu+8rh4XBCUi0Bn+rRSnlTeZrmmHYhRoQgBTIYiNCDW/vPHHDP6mG5mcnWSV5A+SNLRMNJ++xCcGqp+GpHqX9ZfaJcg0FKmmWAZK3j9uL8v/cqZqE=,iv:M0wJaSzO65pAuJw98DANom69eIjm7qRKF1c2x9gfgwg=,tag:PzMqK2pTgSoLZ9xyqkjiHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
