apiVersion: v1
kind: Secret
metadata:
    name: mealie-postgres-superuser
    namespace: db
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:X78sRcBGzy0=,iv:PV81on/GKTJWCSoQhwpi0+gIB2DP1fH3dEI05NZJPJY=,tag:tdpGjFTlnkmguFdg8YKLOg==,type:str]
    password: ENC[AES256_GCM,data:RU44ry/Hm016Mmi51YaM4NdWT1AdXcmXvHMToiIU1C8=,iv:9bvhPoZPo96MZYfQwKECr6c3BPJZMuGJm+j8WH3x9hE=,tag:liVKA8OlYE6Ku605D4KdXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVGVOVVBJS0dmeDM4OWdu
            dlFXTFJRWkdWYitJMmhFZ2ZSVW9JUXhvbVFJCkgyc2xodGNFSVRzZU1jSXVHaWM1
            MlI4V0xKOGxMRlVrNHFZd0hLQk43S00KLS0tIFZwUzlPOE91SHhrVDk4RWVpQ1Nz
            V1YyYzg3MnAwbG9xSTFkeG5zaGtoWk0KHiw5yrQgupzUyCpIXYW5kN7hSpB5rmkg
            0IvMhCvaAaONjwvWfJF8MsGKl215uGHAkDGCUYfFKdM+yPd/fnOGWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T19:15:44Z"
    mac: ENC[AES256_GCM,data:ZTKT0OSRjmP4KHoZeSv7SLe9m0Z0rabZANa+h/IBFtju3YCVmOnzvnQenahdh4aueGw+LNHYMjXpDBlV2h9WNzwz4N1IAEJzLDlNGfr+dSa2AyP0sDSMoXUgjpmS/XRGP5vzNmLOwqaVBprxJwDYb0TNrhAxKzQ6QWUD14ID1+M=,iv:Db+imhw9kza9+aavID0glv37Q5ejvXvOdaLQLgerSVw=,tag:H86ez/AfmPJXyZ0L7A8zrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
