apiVersion: v1
kind: Secret
metadata:
    name: postgres-user-teslamate
    namespace: db
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:hQdFlutXupIS,iv:A7RZ07Bt+TIqPl1/ljkvx6nx4el6/N0f766bVdsDus8=,tag:Rkv3t71oT/otntq1nU256g==,type:str]
    password: ENC[AES256_GCM,data:2pqJ0xV/7L60MdYDLwS32o+gbopMjCFbuu9/0Eey9VA=,iv:QiThCdc2jWEONESDsqTDjWp2jUsKbNAa6YQ9AzYgZ9E=,tag:SnONc3Hqul8wiRslL1ZLyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcWE1MWF0SURSMzRqOXA2
            VVhPZ1pSdDhLOW1mSXY5N0xNVGhzWUFyaW5rCnBuQU1yTmpkQVZ5bFpmMjdhZElh
            ME1kQ0lkZTV6eTdxUFhwZTVnSWduT0UKLS0tIHpIdGdSWHppRDJ4aTVGT1gyY0dW
            dGJpVmZOM1luVVhVOG9ScWFpdkVvN3cKNpOQ5PiE7LgnkX0EmpzqG1hzDO8EDYM4
            dN6wQxZ8lPaae5ZeL2kQi9RS2FR+ILtQyIbFDb2qpRKw2pGhDC3bYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T05:50:59Z"
    mac: ENC[AES256_GCM,data:+t/FVHwQFwCG6oXjAdmZBYtUL1FJ6nPJw5qfOPmTUMnQ+xyfHjlGZ+EUkxXpeqTmRSB7l4F5GUuKhRDPBIqR5T/67u1sbqXwc2hAYPBbMyRw2gwyJnqqxtDs3XZBXALALTWxd+/yZrXrAs51gO/zlS/Gat4Mw8WMk2+JZUCwPME=,iv:17HFG+eIUxU3LMgp1z01FJqi78NE7wVhEhYD7ae9a48=,tag:G1eFaeMeGGK4B3CqZJ9MQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
