apiVersion: v1
kind: Secret
metadata:
    name: satisfactory-secret
    namespace: games
stringData:
    SERVERPASSWORD: ENC[AES256_GCM,data:IsdYkcWJsJ1mKar0f34BEA==,iv:WEwXYX6VV2r2/HtL0QwsZvCnPYmh1k9inN3QViD/Ekc=,tag:q5T4URZkzmOQXFC+it7vsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxR1N0b3h3S1VCTk45QnFP
            OVM4aS9oNnA4OHNlQ1Aranp2TEFSclRMMGd3Cm9hNG5ZYTBYcGNWdTRVQjJRcENw
            K2RQRWlrdC9hcjN4MmNGV1lNeFdzUkEKLS0tIG1iRWNMNm9ZZUhuYnJkekRSTGtY
            T0RDMFNyOFNDUXpjb1NPRngyK094UjAKjamUOjqDBbZ8BMM2mDJy3LGYtP3BiIyN
            8ZQSHjX3UIxwtmVxgWmHv/eWN/uuVzMymeeQ/MxHya2wfsbN18fzOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T17:59:37Z"
    mac: ENC[AES256_GCM,data:gFhi9thRvbPbqySxxOHtskMwkhRlHPVTXbNudjYFPFjTp0Yr7cV2MoJu4bLyIa/sTKHwQWBL7SLrpkF5yGVANuuVnX7OxvY5tYuPTrfiE80dXyAM1VebfXUisL918WNcBe/ZQfVXQJ5KYIo+LB0NbAGXlrZ9SJ+F8osOOuVWXYs=,iv:nXKlfNpVqP/ZkKhFZzzEU8vP5T1TrS4pOgQkOa8xRA4=,tag:0lW1Fc4JAYnr/ASeCiws+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
