apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:gSTFt+HWD2XXeDdQTdYgIxs2pDNaxQtpUsXX2Bvq6k8=,iv:/C1gKNWX3As0p5KXCowrgvXfHQt9OKnNDbAps6owmxM=,tag:USjK8aK+yKiDGmfBjXn9Cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkV3c2SDVUMWR0WHByWE56
            SjVOc2dZTE9UVWFxVGF2TEMzS3R3ZHNWeURJCjBLdlF3WjR6TUMrSnNGMlg1dUlN
            VmJjaXhycGt3SnRIUkFkQ2EvVUI4dlEKLS0tIDgvcUtiTG5TVncvMU1oaUF3OTJj
            TFRkMXpDYzlBc1cyaU8yQkNNWnJ3dFUK/vAQM1zZcrtGKoKauxeX4NOJrB4VUiZT
            0kh6cMT0GioiVHmRvRxIbVUHR8vVSDPEEmC3z/xwiL1bjUY6Y+R4zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-23T03:24:05Z"
    mac: ENC[AES256_GCM,data:a+BDgihgMdt6FcK3BQASk4rKVcJsPffdBqrOzcco0SdfuZS/Ju0diFxUW1UTtN5EE5VdBwQa2zfbJrHTM1hRM2WvYF3+lFE1wpqLBhdX2hLquVYAh5DHKoTBj5GbRfqF7/wym32WzIvH9C/u2+zooPyODuOBbLe8JAEpRLZTHK0=,iv:QEkAXxD/HLAbI/48hESD7HC+1d1uzqy9p8P0BOBr5+M=,tag:ouqY+Bm6DrDumKoWB20u5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
