apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:MkFcVXBjYjm7yM4SSi/sKfs/doNRy+dhbX4w9v3+voU=,iv:tsaDp/k7OZQJLLf6aVzfUoIEtoY4dv2NvorNL9suZPs=,tag:6jBADG/GHOVPtxIH3a05Lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQUZnMGFXc0FzWkpzdDQx
            Z3dCcXZKQXpBZFByb1BKZ3lOZCtmRk9iZnpzCkZGWXlrY0k3V1RWSWg5VUZtcWdr
            LzNxcTFYTHplRlZTSlpUNU9RQWtFY00KLS0tIDNIdlIreGttMHI3NFk3TFRNVGFS
            OW8vd0xGcmhrYXh3WlE5ZE1wWE9iQ3cK7k6AwaTWJIy0iv34nZUn0VlkkL9mm6mE
            JgOTP5ZvTARVn+Za2qCRBM9LJI5zvXbBofD1yGwv1t+WatmGD7phug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-02T00:41:47Z"
    mac: ENC[AES256_GCM,data:52/uvE2XW4TrFuMGtHBi2Po+c9w6tM6028/BHZXIeaEdsBFVCYelFhP7fL4pAsThai2b/cD2aon1wOIDGNKKU7vQkhb2GuSfde46m8J93XRoZqQQfm/SOcmj1csTIcwrimtv7FfOQRIfP9MQjj5RyFacuoeg5p7muDntstlxZdU=,iv:Sa098W1/t7eE4RFt5laQbYaupaGxpm6wgsmAZHCW9Sk=,tag:+nsmpRVkBUjQnzFbpWKUhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
