apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:qazS3rxytOO6sMDdn0Eya58VuSzVKsl3RfFpwOktA3izKk8WCa5VPA==,iv:QR7No+xjha6NuPxy+9UnEld7zSaq0enAnVAvOXMi4Pg=,tag:So2fDvwwcq6JdsfH8s0jrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ruxdp45mj6tc80n6fu3x5xvqccl963ms8qln8sah6plxyvcj47st7u2yf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKS203Rmc1MVpLclZoWFBz
            cnoyQXhEZkx4YlVZYlQrTFdMSm1aNWRCeW13ClVLTys5VHFZaWV1bEZad21LS3lY
            M0pUcVNaN3VhT0FuaEV5NFRYa3dKdkEKLS0tIFZUelZnd1kvSGsrWFR5RlVVZGY0
            R2FZdXZvT0toNkJGUktOUHB2bVg1dDAKN/Bazmm5rIJfpwZ7OnnGZ2kUlqC5sS6k
            IbDrSo0bjIyXSbKt4eJIPPCMuIvbzBqvMcQftPZyxyqyrtQNlWebqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-23T03:24:05Z"
    mac: ENC[AES256_GCM,data:PRRQsAGV2s4rBEriv1brchNovXsO8eHUACBczuCGWB7sgDV7A2+2m9Ss0Vpg/vhPIJd7WcC3Vi8+SSCl8ogDr23BmHjMeyPUrY4stqg5gDjyewqtvcizrCMXo2Dwefnncv4b37v+OGc3BeyGPIKcombPm2Puq1eKgfU7XfQr9Hk=,iv:iwvj8Lk0Z71L2GmCdhynVchA+XMJdBZLd1u7CYat9I0=,tag:znC8lDAFlnLue9Xws6fBbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
